%YAML 1.1
# ^-- ATTN: [2019-12-31] If you use a later version, Github will fail
#     with a bogus error message "You have an error in your yaml syntax".
# -*- coding: UTF-8, tab-width: 4 -*-
---

on:
    push:
        branches:
          - '*'

jobs:
    job_npm_test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version:
                  - '16.x'
                  - '20.x'

        steps:
          - uses: actions/checkout@v4
          # We cannot use ghciu because ghciu uses this package.
          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v4
            with:
                node-version: ${{ matrix.node-version }}
          - run: npm install .
          - run: npm link .
          - run: npm audit
          - run: npm test


...
